{{- if .Values.angular.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: training-angular
  namespace: {{ .Values.namespace }}
spec:
  defaultBackend:
    service:
      name: training-angular
      port:
        number: 80
  rules:
  - host: {{ .Values.angular.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: training-angular
            port:
              number: {{ .Values.angular.service.port }}
{{- end }}